export const TIPS = {
  // Header
  provider: "Which LLM makes the decision. Only providers with a key in mvp/.env appear here.",
  model: "Leave empty to use the provider's default model. Type a model ID to try another one.",
  save: "Save the current scene as a new vignette file with no label. Label it later, then mvp.py tests it.",
  help: "How to use the playground.",

  // Scene
  preset: "Load a test scene from mvp/vignettes. The scenes are grouped by the answer a person expects.",
  expected: "The action a person expects the robot to take in this scene.",
  preset_note: "Click to read the full note.",
  reset_section: "Set this card back to the values in the preset.",
  not_measured: "Not measured. The field is left out of the JSON, as a sensor node does when it cannot measure it.",
  room: "What the audio node hears in the room.",
  person: "The one person the robot might talk to. A dot means you changed something from the preset.",
  robot_section: "What the robot itself did. The app updates this after each turn.",
  never_spoke: "Set to never: the robot has not spoken in this scene.",
  conversation: "What was said so far, oldest first. The model reads it, so a reply can follow on from earlier turns.",
  clear_conversation: "Forget what was said. The next reply starts with no history.",
  noise_level: "How loud the room is. Quiet or moderate rooms suit speech. In a loud room the robot may not be heard.",
  speech_now: "Someone in the room is talking right now.",
  person_present: "Clear this to remove the person. With nobody present, the robot stays silent and no model call happens.",
  distance_m: "How far the person is from the robot, in metres. Rule R5 greets within about 3 m.",
  facing_robot: "The person faces the robot. Facing is one of the signals for a greeting (R5).",
  gaze_at_robot_s: "Seconds the person has looked at the robot. Empty means not measured. 0 means not looking.",
  motion: "Approaching, leaving, passing, or stationary. Someone passing without facing the robot is in transit (R3).",
  activity: "What the person is doing. The robot does not interrupt someone working unless they look at it (R4).",
  in_conversation: "The person talks with someone else. Rule R1: never greet them. The post-filter enforces this in code.",
  bystanders: "Other people in view. They are not the person the robot would address.",
  bystander_distance: "This bystander's distance from the robot, in metres.",
  bystander_facing: "This bystander faces the robot.",
  bystander_talking: "This bystander is in a conversation.",
  add_bystander: "Add another person to the scene.",
  remove_bystander: "Remove this bystander.",
  engaged: "The robot is already in a conversation. Transcripts only exist while this is on. Send turns it on.",
  is_speaking: "The robot is talking right now. It never starts to speak over itself (post-filter).",
  last_spoke_s_ago: "Seconds since the robot last spoke. Empty means never. Under 30 s, rule R2 blocks a new greeting.",
  consecutive_no_response: "How many times this person ignored the robot. At 2, the robot stops talking to them (R2).",
  raw_json: "The exact context the server receives. Edit it to set fields that have no control, then press apply.",

  // Chat
  input: "Type what the person says to the robot. It goes into target.speech.partial_transcript.",
  send: "Send what you typed. The robot decides whether to reply, and what to say. Enter also sends.",
  check: "Ask the robot to decide with no one speaking. Use it to test whether the robot starts a conversation.",
  unfinished: "Mark the next message as cut off mid-sentence. The robot should wait, not reply.",
  plus5: "Move time forward 5 seconds. The robot's 'last spoke' timer and past decisions age by 5 s.",
  plus30: "Move time forward 30 seconds. Use it to get past the 30 s greeting cooldown (R2).",
  ignored: "The person did not answer the robot. Adds 1 to consecutive_no_response. Twice stops the robot (R2).",
  reset: "Load the preset again and clear the chat.",

  // Robot bubble
  rubric: {
    invitation: "Invitation: 1 = ignoring the robot, 5 = clearly seeking contact.",
    interruption_cost: "Interruption cost: 1 = idle, 5 = deep in work or conversation.",
    urgency: "Urgency: 1 = nothing needs saying, 5 = looks lost or distressed.",
    redundancy: "Redundancy: 1 = never engaged, 5 = the robot just spoke to them.",
    ambient_fit: "Ambient fit: 1 = speech would be inaudible or intrusive, 5 = well suited.",
    addressivity: "Addressivity: 1 = unclear who to address, 5 = one clear person.",
  },
  action: {
    greet: "greet: the robot starts a new conversation.",
    respond: "respond: the robot replies to what the person said.",
    wait: "wait: a good moment may come soon. Stay ready, but say nothing.",
    remain_silent: "remain_silent: say nothing. Nothing is likely to change soon.",
  } as Record<string, string>,
  voice: "Volume / rate / pitch the model chose for the line. Later these become SSML for text to speech.",
  rule: "The rule that most drove the decision, as the model reports it.",
  category: "The kind of situation the model saw.",
  confidence: "The model's own confidence. It is poorly calibrated, so do not trust it as a score.",
  recheck: "How long the model suggests before deciding again.",
  blocked: "The model chose to speak, but a hard rule in postfilter.py overrode it. The line is not said.",
  changes: "The scene fields you changed since the previous turn.",
  latency: "Decision is call 1. Line is call 2, which only runs when the robot speaks.",
};
